import { useState, useEffect } from "react";
import {
  Modal,
  Box,
  Typography,
  CircularProgress,
  Button,
} from "@mui/material";

import { BACKEND_ROOT } from "./App";
import { MODAL_STYLE } from "./LandmarkViewModal";

export default function AIModal({ open, close, landmarkId }) {
  const [wisdom, setWisdom] = useState("");
  const [visibleIdx, setVisibleIdx] = useState(0);

  const showGradually = () => {
    if (visibleIdx > wisdom.length) {
      return;
    } else {
      setVisibleIdx((prev) => prev + 1);
      setTimeout(showGradually, 15);
    }
  }

  useEffect(() => {
    if (!open) {
      return;
    }
    fetch(`${BACKEND_ROOT}/landmark/${landmarkId}/wisdom`).then((rsp) => {
      return rsp.json();
    }).then((json) => {
      setWisdom(json.text);
      setVisibleIdx(0);
      showGradually();
    }).catch((err) => {
      console.error(err);
    });
  }, [open, landmarkId]);

  return (
    <Modal open={open} onClick={close}>
      <Box sx={{ ...MODAL_STYLE, width: "70%" }} onClick={(e) => e.stopPropagation()}>
        {!wisdom ? (
          <CircularProgress />
        ) : (
          <Box>
            <Typography variant="h5" sx={{ textAlign: "left" }}>🤖: {wisdom.substring(0, visibleIdx)}</Typography>
            <Box sx={{ pt: "1em" }}>
              <Typography variant="caption">
                Caution: this response was generated by AI, and so may contain inaccurate information.
              </Typography>
            </Box>
          </Box>
        )}
        <Box sx={{ pt: "1em" }}>
          <Button onClick={close}>Back to landmark</Button>
        </Box>
      </Box>
    </Modal>
  )
}